"""The lab's IKE secrets: the pre-shared key, and the placeholders that keep it out of git.

The pre-shared key lives in secrets/dmvpn_psk on the lab host (mode 600, not in git). Until the first rotation there
is none and lab.conf's DMVPN_PSK — the public lab default — is used. Rendered files never contain the key:

  nodes/<vyos>/vyos_config.txt   carries @@DMVPN_PSK@@, filled in when the file is pushed (vyos_push.py, vyos_console.py)
  nac/data/devices.nac.yaml      no key at all: the group's ${dmvpn_psk} comes from nac/data/secrets.nac.yaml (not in
                                 git), a global variable written by gen_configs.py

mask() hides keys and private keys in anything shown (show commands, configuration history, drift reports): a secret
becomes <secret …abcd>, the last characters of its SHA-256, so a change still shows as a change."""
import hashlib
import os
import re
import secrets as _s
import string
import subprocess
import time
from pathlib import Path

LAB = Path(__file__).resolve().parents[1]
DIR = LAB / "secrets"
PSK = DIR / "dmvpn_psk"
PLACEHOLDER = "@@DMVPN_PSK@@"


def _labconf_psk():
    return subprocess.run(["bash", "-c", f'source "{LAB}/lab.conf" >/dev/null 2>&1; printf %s "$DMVPN_PSK"'],
                          capture_output=True, text=True).stdout


def psk():
    return PSK.read_text().strip() if PSK.exists() else _labconf_psk()


def psk_info():
    """Where the key comes from and since when — never the key."""
    if PSK.exists():
        return {"source": "secrets/dmvpn_psk (rotated)", "since": PSK.stat().st_mtime, "fingerprint": fingerprint(psk())}
    return {"source": "lab.conf DMVPN_PSK (the public lab default)", "since": None, "fingerprint": fingerprint(psk())}


def fingerprint(value):
    return hashlib.sha256(value.encode()).hexdigest()[-8:]


def new_psk(length=40):
    """Letters and digits only: nothing IOS's keyring or VyOS's quoting could misread."""
    alphabet = string.ascii_letters + string.digits
    return "".join(_s.choice(alphabet) for _ in range(length))


def set_psk(value):
    DIR.mkdir(exist_ok=True)
    DIR.chmod(0o700)
    if PSK.exists():
        (DIR / "dmvpn_psk.previous").write_text(PSK.read_text())
        (DIR / "dmvpn_psk.previous").chmod(0o600)
    tmp = PSK.with_suffix(".tmp")
    tmp.write_text(value + "\n")
    tmp.chmod(0o600)
    os.replace(tmp, PSK)
    return {"since": time.time(), "fingerprint": fingerprint(value)}


def fill(text):
    return text.replace(PLACEHOLDER, psk())


def nac_secrets_yaml():
    """nac/data/secrets.nac.yaml: the key as a global variable of the Network-as-Code model."""
    return ("---\n# GENERATED by tools/gen_configs.py from secrets/ — NOT in git. The IKE pre-shared key, as a global variable\n"
            f"iosxe:\n  global:\n    variables:\n      dmvpn_psk: \"{psk()}\"\n")


MASKS = [
    re.compile(r"(pre-shared-key(?: local| remote)?(?: \d)? )(\S+)"),               # IOS keyring
    re.compile(r"(pre-shared-secret )'?([^'\s]+)'?"),                               # VyOS
    re.compile(r"(authentication (?:plaintext|encrypted)-password )'?([^'\s]+)'?"),
    re.compile(r"(private key )'?([^'\s]+)'?"),                                     # VyOS pki
    re.compile(r"(dmvpn_psk: )\"?([^\"\s]+)\"?"),
]


def mask(text):
    if not text:
        return text
    for rx in MASKS:
        text = rx.sub(lambda m: f"{m[1]}<secret …{fingerprint(m[2])[-4:]}>", text)
    return text.replace(psk(), "<secret>") if len(psk()) >= 8 else text
